=== swathi121/Marks-Workspace/html/XML/StudRules.dtd
<!ELEMENT inistitute(student+)> 
<!ELEMENT student(rollno,name,mobileno*,address)> 
<!ELEMENT rollno(#PCDATA)> 
<!ELEMENT name(#PCDATA)> 
<!ELEMENT address(hno,colony,city)>
<!ELEMENT hno(#PCDATA)> 
<!ELEMENT colony(#PCDATA)> 
<!ELEMENT city(#PCDATA)> 
<!ATTLIST student course(java|html|oracle) "html"> 
<!ATTLIST student type CDATA #IMPLIED>
<!ATTLIST address state CDATA "AP" >

=== swathi121/Marks-Workspace/html/XML/stud.xml
<!DOCTYPE institute SYSTEM "StudRules.dtd">
<inistitute>
<student course="java" type="regular">
<rollno>1234</rollno>
<name>swathi</name>
<mobileno>9902800633</mobileno>
<address state="AP">
<hno>2-82</hno>
<colony>tharalapally</colony>
<city>warangal</city>
</address>
</student>
</inistitute>
